env: "local" # Возможные окружения - local, dev, prod
storage_path: "postgresql://postgres:password@localhost:5432/db-name" # local хранит данные от БД
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 30s